/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package encofx.lib.dialogs;

import encofx.lib.renderers.FourSidesGradientPanel;
import encofx.lib.renderers.TwoSidesGradientPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Yves
 */
public class SidesGradientDialog extends javax.swing.JDialog {

    private ButtonPressed bp;
    private Mode mode = Mode.Two_Sides;
    private TwoSidesGradientPanel twosides;
    private FourSidesGradientPanel foursides;
    
    public enum ButtonPressed{
        NONE, OK_BUTTON, CANCEL_BUTTON;
    }
    
    public enum Mode{
        Two_Sides, Four_Sides;
    }
    
    /**
     * Creates new form GradientDialog
     * @param parent
     * @param modal
     */
    public SidesGradientDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bp = ButtonPressed.NONE;
    }
    
    public Color[] showTwoSidesDialog(Color[] cs){
        mode = Mode.Two_Sides;
        init(cs);
        setLocationRelativeTo(null);
        setVisible(true);
        
        if(bp.equals(ButtonPressed.OK_BUTTON)){
            return getColors();
        }else{
            return cs;
        }
    }
    
    public Color[] showFourSidesDialog(Color[] cs){
        mode = Mode.Four_Sides;
        init(cs);
        setLocationRelativeTo(null);
        setVisible(true);
        
        if(bp.equals(ButtonPressed.OK_BUTTON)){
            return getColors();
        }else{
            return cs;
        }
    }
    
    private void init(Color[] cs){
        twosides = new TwoSidesGradientPanel(mainPanel.getWidth(), mainPanel.getHeight());
        foursides = new FourSidesGradientPanel(mainPanel.getWidth(), mainPanel.getHeight());
        switch(mode){
            case Two_Sides:
                lblColor3.setVisible(false);
                btnColor3.setVisible(false);
                lblColor4.setVisible(false);
                btnColor4.setVisible(false);
                lblColor1.setBackground(cs[0]);
                lblColor2.setBackground(cs[1]);                
                twosides.setColor1(cs[0]);
                twosides.setColor2(cs[1]);
                mainPanel.setLayout(new BorderLayout());
                mainPanel.add(twosides, BorderLayout.CENTER);
                break;
            case Four_Sides:
                lblColor3.setVisible(true);
                btnColor3.setVisible(true);
                lblColor4.setVisible(true);
                btnColor4.setVisible(true);
                lblColor1.setBackground(cs[0]);
                lblColor2.setBackground(cs[1]);
                lblColor3.setBackground(cs[2]);
                lblColor4.setBackground(cs[3]);                
                foursides.setColor1(cs[0]);
                foursides.setColor2(cs[1]);
                foursides.setColor3(cs[2]);
                foursides.setColor4(cs[3]);
                mainPanel.setLayout(new BorderLayout());
                mainPanel.add(foursides, BorderLayout.CENTER);
                break;
        }
        setSize(410,200);
    }
    
    private Color[] getColors(){
        if(mode==Mode.Two_Sides){
            return new Color[]{
                    lblColor1.getBackground(),
                    lblColor2.getBackground()
                };
        }else{
            return new Color[]{
                    lblColor1.getBackground(),
                    lblColor2.getBackground(),
                    lblColor3.getBackground(),
                    lblColor4.getBackground()
                };
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        lblColor1 = new javax.swing.JLabel();
        btnColor1 = new javax.swing.JButton();
        lblColor2 = new javax.swing.JLabel();
        btnColor2 = new javax.swing.JButton();
        lblColor3 = new javax.swing.JLabel();
        btnColor3 = new javax.swing.JButton();
        lblColor4 = new javax.swing.JLabel();
        btnColor4 = new javax.swing.JButton();
        OK_Button = new javax.swing.JButton();
        Cancel_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 160));
        getContentPane().setLayout(null);

        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel);
        mainPanel.setBounds(10, 11, 112, 110);

        lblColor1.setBackground(new java.awt.Color(0, 0, 0));
        lblColor1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblColor1.setOpaque(true);
        getContentPane().add(lblColor1);
        lblColor1.setBounds(132, 11, 100, 23);

        btnColor1.setText("Change first color");
        btnColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColor1);
        btnColor1.setBounds(236, 11, 150, 23);

        lblColor2.setBackground(new java.awt.Color(255, 255, 255));
        lblColor2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblColor2.setOpaque(true);
        getContentPane().add(lblColor2);
        lblColor2.setBounds(132, 40, 100, 23);

        btnColor2.setText("Change second color");
        btnColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColor2);
        btnColor2.setBounds(236, 40, 150, 23);

        lblColor3.setBackground(new java.awt.Color(0, 0, 204));
        lblColor3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblColor3.setOpaque(true);
        getContentPane().add(lblColor3);
        lblColor3.setBounds(132, 69, 100, 23);

        btnColor3.setText("Change third color");
        btnColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColor3);
        btnColor3.setBounds(236, 69, 150, 23);

        lblColor4.setBackground(new java.awt.Color(255, 0, 0));
        lblColor4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblColor4.setOpaque(true);
        getContentPane().add(lblColor4);
        lblColor4.setBounds(132, 98, 100, 23);

        btnColor4.setText("Change fourth color");
        btnColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnColor4);
        btnColor4.setBounds(236, 98, 150, 23);

        OK_Button.setText("OK");
        OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OK_Button);
        OK_Button.setBounds(286, 127, 100, 23);

        Cancel_Button.setText("Cancel");
        Cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_Button);
        Cancel_Button.setBounds(180, 127, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_ButtonActionPerformed
        bp = ButtonPressed.OK_BUTTON;
        dispose();
    }//GEN-LAST:event_OK_ButtonActionPerformed

    private void Cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_ButtonActionPerformed
        bp = ButtonPressed.CANCEL_BUTTON;
        dispose();
    }//GEN-LAST:event_Cancel_ButtonActionPerformed

    private void btnColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor1ActionPerformed
        Color c = JColorChooser.showDialog(this, "Choose a color...", lblColor1.getBackground());
        lblColor1.setBackground(c);
        switch(mode){
            case Two_Sides:
                twosides.setColor1(c);
            case Four_Sides:
                foursides.setColor1(c);
        }
    }//GEN-LAST:event_btnColor1ActionPerformed

    private void btnColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor2ActionPerformed
        Color c = JColorChooser.showDialog(this, "Choose a color...", lblColor2.getBackground());
        lblColor2.setBackground(c);
        switch(mode){
            case Two_Sides:
                twosides.setColor2(c);
            case Four_Sides:
                foursides.setColor2(c);
        }
    }//GEN-LAST:event_btnColor2ActionPerformed

    private void btnColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor3ActionPerformed
        Color c = JColorChooser.showDialog(this, "Choose a color...", lblColor3.getBackground());
        lblColor3.setBackground(c);
        foursides.setColor3(c);
    }//GEN-LAST:event_btnColor3ActionPerformed

    private void btnColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor4ActionPerformed
        Color c = JColorChooser.showDialog(this, "Choose a color...", lblColor4.getBackground());
        lblColor4.setBackground(c);
        foursides.setColor4(c);
    }//GEN-LAST:event_btnColor4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SidesGradientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SidesGradientDialog dialog = new SidesGradientDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_Button;
    private javax.swing.JButton OK_Button;
    private javax.swing.JButton btnColor1;
    private javax.swing.JButton btnColor2;
    private javax.swing.JButton btnColor3;
    private javax.swing.JButton btnColor4;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblColor2;
    private javax.swing.JLabel lblColor3;
    private javax.swing.JLabel lblColor4;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
